### ISSUE TITLE
when add authentication in resource, the page can not show

### ISSUE THREAD

**Issue by wenzhixue** [juanique/django-tastytools#11]
when  i add  authentication = ApiKeyAuthentication() to the resources... 
the doc can not be generated.... cos when i click the link... i find out it automatically called
"GET /api/v1/category/schema/ HTTP/1.1" 401 0  .... which has no permission... i must pass username and api_key as other request  
is there any way to solve this problem ?  thanks

**Comment by juanique** [comment]
I've never used `ApiKeyAuthentication()` so I can't tell you how to get around this problem. I'll look into it when I have some time. In the meantime, feel free to browse the code and make suggestions, probably all you need is to send the api key when sending the GET request for the schema, right?.

**Comment by jawache** [comment]
I've just hit the same problem - hacked around it in my code base but i think the best solution would be to change the js side so that:

$.ajaxSetup({ beforeSend:function (xhr, settings) {
    // ApiKey daniel:204db7bcfafb2deb7506b89eb3b9b715b09905c8
    var user = <GET FROM QUERY STRING>
    var key =  <GET FROM QUERY STRING>
    if (user && key) {
        var token = "ApiKey " + user + ":" + key;
        console.log("Authorisation " + token);
        xhr.setRequestHeader('Authorization', token);
    }
}});

So if you have an API key you can view the docs just by going to:

http://127.0.0.1:8000/api/tastytools/doc/?apikey=asim:123123123123123

Then any subsequent ajax request from that page will take the apikey from the QP and send that also.

Either that or just always send whatever is in the QP for the page to the subsequent backbone requests.

**Comment by juanique** [comment]
Thanks @jawache .
