### ISSUE TITLE
Specify License, Upload to PyPi

### ISSUE THREAD

**Issue by SeanHayes** [juanique/django-tastytools#13]
I'd really like to use this in a project I'm working on, but there's no license specified and there's no release on PyPi.

**Comment by juanique** [comment]
Hi @SeanHayes, thanks for your interest in django-tastytools.

I don't know much about the different kind of licenses available and which one is more suitable for this project. My idea is that everyone can benefit from it as much as possible so it won't be too restrictive.

Please give me a week or so to document myself about the subject. In the meantime feel free to include this code in your project and make sure to update it once the license details are made available.

As for PyPi, there is a whole lot of details that I would like to get fixed before making a release there. Since there I've seen some interest in the project from different people, I will try to put more effort on the development of the lib to make it more stable and usable.

**Comment by SeanHayes** [comment]
If you're looking for a non-restrictive license, I'd recommend the BSD license, it's the same one the Django project uses, and many Django related projects use it as well.

**Comment by dbrgn** [comment]
Yes please, license and pypi! :)

django-tastypie uses the BSD 3-clause (https://github.com/toastdriven/django-tastypie/blob/master/LICENSE), so that's what I'd suggest using.

For more information, see http://www.tldrlegal.com/

**Comment by JDSchmitz** [comment]
Any update on the licensing?  I'd really like to use this as well.

**Comment by juanique** [comment]
Ok, yeah... this is the thing, i'm copying the response from another issue. I will add this to the README:

I've been working on a new version of this project with the objective to clean up a lot of unnecessary code and properly isolate the different functionalities. Because of this, I haven't updated the current code too much, so it is very likely to become outdated and not able to keep up with the new tastypie versions.

Basically, I'm splitting the code into 3 parts:

https://github.com/juanique/django-chocolate - Which handles mockup models creation for unit testing
https://github.com/juanique/django-tastydocs - Which handles automatic web tastypie api documentation (it depends on django-chocolate)

And I still need to define a 3rd part which will cover automatic test generation for fuzzy testing and code quality.

Since django-tastytools does all of this (and a little bit more), it would be useful to me if you could tell me exactly what are you using it for. The new code base is not yet ready but at least the first two parts are quite functional, a lot of documentation is missing though....

These two new projects I have, they both have a LICENSE file, I'll copy it over to this project just so you can feel free to use it. But I would encourage you to check out the new projects though.

**Comment by juanique** [comment]
Added LICENSE. Will not upload to PyPi in favor of the new code base.
