### ISSUE TITLE
example data don't work

### ISSUE THREAD

**Issue by bclermont** [juanique/django-tastytools#15]
I tried with latests tastypie version.

and tastypie.api.Api.urls don't register at all the example nested resource.

is that was suposed to work in first place?

**Comment by juanique** [comment]
Hi Bruno,

I've been working on a new version of this project with the objective to clean up a lot of unnecessary code and properly isolate the different functionalities. Because of this, I haven't updated the current code too much, so it is very likely to become outdated and not able to keep up with the new tastypie versions.

Basically, I'm splitting the code into 3 parts:

https://github.com/juanique/django-chocolate - Which handles mockup models creation for unit testing
https://github.com/juanique/django-tastydocs - Which handles automatic web tastypie api documentation (it depends on django-chocolate)

And I still need to define a 3rd part which will cover automatic test generation for fuzzy testing and code quality.

Since django-tastytools does all of this (and a little bit more), it would be useful to me if you could tell me exactly what are you using it for. The new code base is not yet ready but at least the first two parts are quite functional, a lot of documentation is missing though....

**Comment by bclermont** [comment]
Oh, thanks. 

I'm trying to have auto generated doc AND data example.

I have looked at django-chocolate, if it work it's not implemented the same way.

**Comment by juanique** [comment]
It is not implemented in the same way but it should be easier to user.

I encourage you to checkout the django-chocolate tests code, which shows usage examples:

https://github.com/juanique/django-chocolate/blob/master/test_project/blog/tests.py

**Comment by bclermont** [comment]
I just switched to django-tastytools and it work!

you should say all this in the readme file :)
